### ISSUE TITLE
side bar on pages like support/about still sends people to the wrong place

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#82] opened 2016-01-03 17:27 UTC
If not covered by #16 and #24 this needs to be figured out and fixed!

**Comment by mtb-za** [comment] 2016-01-18 12:16
What do you mean by this? That it does not go to the top of the page?

**Comment by JosephMcArthur** [comment] 2016-01-18 12:17
When you click it, you don't arrive at the right hash

On 18 January 2016 at 12:16, Martin Bentley <notifications@github.com>
wrote:

> What do you mean by this? That it does not go to the top of the page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/backend/issues/82#issuecomment-172512923>.
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by JosephMcArthur** [comment] 2016-01-18 12:19
e.g share and code stick you at the bottom of the respective pages.

Clearly also an issue that https://openaccessbutton.org/support goes to
https://openaccessbutton.org/support#fund automatically for some reason.

On 18 January 2016 at 12:17, Joseph Mcarthur <joseph.mcarthur.10@gmail.com>
wrote:

> When you click it, you don't arrive at the right hash
>
> On 18 January 2016 at 12:16, Martin Bentley <notifications@github.com>
> wrote:
>
>> What do you mean by this? That it does not go to the top of the page?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/OAButton/backend/issues/82#issuecomment-172512923>.
>>
>
>
>
> --
> Joseph McArthur
> Assistant Director: Right to Research Coalition
> <http://righttoresearch.org/>
> Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
> Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
> Skype: joseph_mcarthur
> Linkedin <http://linkd.in/1BgZ1jU>
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by mtb-za** [comment] 2016-01-18 13:53
I will see what I can do about this, although I seem to recall trying and failing when I first set it up, because of how I was doing the navigation in the first place. Essentially, each of those is only one page, with the sections not being shown staying hidden until the menu item is clicked. There is probably a better way to do this, so I will have a look.

> Clearly also an issue that https://openaccessbutton.org/support goes to https://openaccessbutton.org/support#fund automatically for some reason.

I think that that one was because there was no copy for a basic support page when I was putting this together, and #fund was just the first item on that menu. So it defaults to that, in the same way that https://openaccessbutton.org/about actually links to https://openaccessbutton.org/about#how

**Comment by JosephMcArthur** [comment] 2016-01-18 13:58
I seeeeeeeeee. If the simple fix for /support is to write a page that
summarizes the section, I'm all for that. Same for /about.

Then all we have left to fix is that it doesn't got to the top of the page!

On 18 January 2016 at 13:53, Martin Bentley <notifications@github.com>
wrote:

> I will see what I can do about this, although I seem to recall trying and
> failing when I first set it up, because of how I was doing the navigation
> in the first place. Essentially, each of those is only one page, with the
> sections not being shown staying hidden until the menu item is clicked.
> There is probably a better way to do this, so I will have a look.
>
> Clearly also an issue that https://openaccessbutton.org/support goes to
> https://openaccessbutton.org/support#fund automatically for some reason.
>
> I think that that one was because there was no copy for a basic support
> page when I was putting this together, and #fund was just the first item on
> that menu. So it defaults to that, in the same way that
> https://openaccessbutton.org/about actually links to
> https://openaccessbutton.org/about#how
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/backend/issues/82#issuecomment-172532211>.
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by mtb-za** [comment] 2016-01-18 14:10
Does not need to be a full page even, just some copy as a landing section on those pages.

**Comment by JosephMcArthur** [comment] 2016-01-18 14:15
Yeah, okay. We'll do that then yes? I'll draft some copy for it.

On 18 January 2016 at 14:10, Martin Bentley <notifications@github.com>
wrote:

> Does not need to be a full page even, just some copy as a landing section
> on those pages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/backend/issues/82#issuecomment-172535303>.
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by mtb-za** [comment] 2016-01-18 14:19
Oh my word that was a stupid bit of thinking on my side.

Fixed the scrolling on both pages.

Apparently having a "scrollTo" command is a bit of a daft idea in this instance, since the anchor to scroll to is a long way down the actual page.

Once we have some copy, I can make the last (I think fairly minor) edit in order to close this.

**Comment by JosephMcArthur** [comment] 2016-01-18 14:22
Amazing. May take me a while to do copy, but I'll do it before launch.

On 18 January 2016 at 14:19, Martin Bentley <notifications@github.com>
wrote:

> Oh my word that was a stupid bit of thinking on my side.
>
> Fixed the scrolling on both pages.
>
> Apparently having a "scrollTo" command is a bit of a daft idea in this
> instance, since the anchor to scroll to is a long way down the actual page.
>
> Once we have some copy, I can make the last (I think fairly minor) edit in
> order to close this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OAButton/backend/issues/82#issuecomment-172538503>.
>



-- 
Joseph McArthur
Assistant Director: Right to Research Coalition
<http://righttoresearch.org/>
Co-Lead/Founder: Open Access Button <http://openaccessbutton.org/>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur
Linkedin <http://linkd.in/1BgZ1jU>

**Comment by mtb-za** [comment] 2016-01-18 14:23
Just tested with some placeholder text, it will be really easy.

Going to close this issue and make a new one, I think, since they are not really related.

The scrolling is fixed.

**Comment by mtb-za** [comment] 2016-02-23 12:53
I have a suspicion that my fix for #91 (and #60) has caused a regression here, and we are seeing this again.

Could someone confirm?

**Comment by mtb-za** [comment] 2016-02-23 13:07
Solved by throwing more javascript at the problem. In this case, a forced scroll to `(0,0)`.

**Closed by mtb-za** 2016-02-23 13:07 UTC
Labels: bug
