### ISSUE TITLE
Requests created on button open rather than submission

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#150] opened 2016-07-04 08:56 UTC
_From @dhimmel on April 9, 2016 20:45_

I believe requests are being created prior to pressing submit. The result is that I have multiple open data requests for the same piece of content in https://opendatabutton.org/account:

![multiple open data button requests](https://cloud.githubusercontent.com/assets/1117703/14406319/62df5600-fe59-11e5-9716-4f504a2b14e8.png)

Not sure exactly how this happened, but I do not I've only submitted requests twice and hence there should only be two requests.

_Copied from original issue: OAButton/odb#59_

**Comment by markmacgillivray** [comment] 2016-07-11 14:28
These are stories (blocks) rather than requests. So yes they are created on button open rather than on click, as intended. But stopping duplicate story for a URL per user should be implemented anyway. Secondarily, this also indicates the lack of clarity to a user on what is the difference between request/blocked/story

**Comment by dhimmel** [comment] 2016-07-11 14:38
> what is the difference between request/blocked/story

Yes! What the heck is a story :confounded:

**Comment by markmacgillivray** [comment] 2016-07-13 11:53
Have updated blocked API to not accept a block from a user who has already been blocked on it. Also updated UI to thank user for support instead of asking for support if user has already been blocked on the URL. The larger problem of what are blocked/story/requests, and what they mean to users, should be considered in the wider ongoing discussion about them. Will be pushing the update to live later today, closing issue now to keep track of what has been done already.

**Closed by markmacgillivray** 2016-07-13 11:53 UTC
