### ISSUE TITLE
Improve mobile nav bar experiance 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/backend#218] opened 2016-09-02 14:51 UTC
Many folks are investing heavily in making their mobile nav bars much better. 

For example https://www.hillaryclinton.com/

It's not common for the hamburger to become a cross when clicked (which is nice I think) and for the nav bars to take up large sections of the screen. The former I think would be great for us, the later is debatable. Just wanted to start an issue where we could collect thoughts.

There is clear room for improvement, currently opening the nav bar produces a tiny scroll bar that is just odd.

**Comment by markmacgillivray** [comment] 2016-10-28 09:01
The nav bar on mobile seems better on most pages but bad on the front page - just a note to myself; some content on the page seems to be forcing the width of the nav bar to stay too wide.

**Comment by JosephMcArthur** [comment] 2016-10-28 10:19
Is the logo's at the bottom, there in issue for this.

However, I think the site's sidebar, even on otherpages, is subpar. Having
to scroll to reach options is a fairly poor UX.

**Comment by markmacgillivray** [comment] 2016-10-28 10:24
Yes, other things need doing too - was just reminding myself to look at this. But yeah, it will be those logos. i'll use the chopped up ones when I have a few minutes to fix it up.

**Comment by markmacgillivray** [comment] 2016-10-28 11:04
@JosephMcArthur is this really an issue that should start with assignment to me? If I go ahead and make changes to mobile nav bar experience then I am making changes to site content, how it appears to users, making decisions on layout etc. These are all things I am capable of doing, and I have a good idea of how to improve the mobile nav bar, but is this an acceptable order? Or should an issue like this start with Megan for user testing, Chealsye for content, then me for commenting on what is possible / not possible? This is the sort of thing that a review of the 3.5 milestone will need to consider, and could be worth discussing at the next Monday meeting.

**Comment by JosephMcArthur** [comment] 2016-10-28 11:24
So, a couple of things here:

* we haven't yet done a user test on mobile, this is something we must
change.
* Currently the way our nav bar works is so far from the norm that I don't
think we have to justify changes through usertesting. As you say, you have
a good impression of what a better navbar looks like, and a basic
implementation of this is likely to be good enough to close this issue.

The useful thing for this would be, an estimation of how much of your time
it would take to close. Then we should add 2 hour of Megan's time onto that
for testing on a few phones.

A bonus would perhaps be a short description of your ideas for how to
improve it. The ideal here would be a simple drawing.

**Comment by markmacgillivray** [comment] 2016-10-28 11:41
OK. I am better at coding than I am at drawing - if everyone is OK with it I'd rather just make a new navbar on the dev site, put in what I think makes sense there, and then it can be tested / copy altered, etc. I'm just being specific about these things to try to ensure I don't upset anyone else by going ahead and doing things on the dev site, where they can be reviewed.

I'll make an alternative mobile nav next week - then what to do once I get something like this finished? Can I assign it to someone else to test / review?

**Comment by markmacgillivray** [comment] 2016-10-28 11:42
I'd rather be able to use the dev site to do development (which I am good at) than to have to resort to drawing (which I am bad at)!

**Comment by JosephMcArthur** [comment] 2016-10-28 13:38
Go straight to coding then. To be clear, this doesn't have to be at all
fancy. Assign to Megan for testing & me for review, do both of us at once.

On Fri, 28 Oct 2016 at 12:43 markmacgillivray <notifications@github.com>
wrote:

I'd rather be able to use the dev site to do development (which I am good
at) than to have to resort to drawing (which I am bad at)!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OAButton/backend/issues/218#issuecomment-256899993>,
or mute
the thread

**Comment by markmacgillivray** [comment] 2016-10-28 13:42
Sure, I don't think it will be fancy - just a fullscreen menu list. I just want to be clear that everyone is happy with the intent of action and roles :)

**Comment by markmacgillivray** [comment] 2016-11-04 10:31
Improved mobile nav is now available on the dev site. Ready for testing. Will assign to @meganwaps and @JosephMcArthur  - let me know if that is the wrong thing to do.

**Comment by JosephMcArthur** [comment] 2016-11-04 10:44
Just looked as I was on the dev site anyway! Thoughts:

- [ ] Colours / icon's could be a bit nicer, but you already know this
* This implementation fixes the UI issues I think. I showed it a few people here and their reaction was complete apathy (in contrast to sadness at the current version)
* A smoother animation for it might be nice, but, that isn't needed. As long as it looks clean & is fast I think that's more important. 
* Some icons wouldn't go amiss, but, aren't needed (again)
- [ ] Open Access Button as the first line should probably be "home"
- [ ] account should be capitalised on mobile & desktop

Generally push forwards here @markmacgillivray, assigning back to you.

**Comment by JosephMcArthur** [comment] 2016-11-04 10:45
Just looked as I was on the dev site anyway! Thoughts:

- [ ] Colours / icon's could be a bit nicer, but you already know this
* This implementation fixes the UI issues I think. I showed it a few people here and their reaction was complete apathy (in contrast to sadness at the current version)
* A smoother animation for it might be nice, but, that isn't needed. As long as it looks clean & is fast I think that's more important. 
* Some icons wouldn't go amiss, but, aren't needed (again)
- [ ] Open Access Button as the first line should probably be "home"
- [ ] account should be capitalised on mobile & desktop

Generally push forwards here @markmacgillivray, assigning back to you.

**Comment by JosephMcArthur** [comment] 2016-11-04 10:45
Just looked as I was on the dev site anyway! Thoughts:

- [ ] Colours / icon's could be a bit nicer, but you already know this
* This implementation fixes the UI issues I think. I showed it a few people here and their reaction was complete apathy (in contrast to sadness at the current version)
* A smoother animation for it might be nice, but, that isn't needed. As long as it looks clean & is fast I think that's more important. 
* Some icons wouldn't go amiss, but, aren't needed (again)
- [ ] Open Access Button as the first line should probably be "home"
- [ ] account should be capitalised on mobile & desktop

Generally push forwards here @markmacgillivray, assigning back to you.

**Comment by markmacgillivray** [comment] 2016-11-04 11:01
@JosephMcArthur how about now?

**Comment by JosephMcArthur** [comment] 2016-11-04 11:11
This is all my taste..

- [ ] remove box around hamburger icon
- [ ] simplify hamburger icon (just 3 lines, not 4 dots & lines)

and generally, the colour scheme feels like its too dark. Contrasts pretty deeply with the nav bars generally design. Wondering if white background, black text & orange / blue lines would be nicer?

**Comment by markmacgillivray** [comment] 2016-11-04 11:23
How about now? Matches better with our nav colours I think. Changed the icon, does it look clearer now?

**Comment by markmacgillivray** [comment] 2016-11-04 11:23
@JosephMcArthur pinging you just to see if you're still looking at it and can give a quick response

**Comment by JosephMcArthur** [comment] 2016-11-04 11:43
Perfect. If @meganwaps can test this on a few mobiles (with browserstack) we're good to close.

**Comment by JosephMcArthur** [comment] 2016-11-24 10:48
@markmacgillivray just re-looking at this. Can we:
- [ ] remove the box around the hamburger
- [ ] remove the greyish 

Otherwise this is good to close. I have tested on android & ios

**Comment by markmacgillivray** [comment] 2016-11-28 12:04
@JosephMcArthur I am not sure what you mean for these, where are you seeing a box round the hamburger? Can you refresh your browser and screenshot it, and tell me which browser you are using? Also where do you mean remove the greyish from? Can do quickly once confirmed.

**Comment by JosephMcArthur** [comment] 2016-11-28 12:07
![image](https://cloud.githubusercontent.com/assets/4953703/20667798/27bca78c-b563-11e6-8340-ff5f360374d4.png)

I see it on desktop chrome, android chrome & on iphone safari.

**Comment by markmacgillivray** [comment] 2016-11-28 12:10
Ah OK, looks different for me. I see what you mean about the box and the greyish now. Will look into it.

**Comment by markmacgillivray** [comment] 2016-11-28 12:16
Weird. It did not show on desktop chrome for me but did on android chrome (which I should have seen in the phone dev mode on desktop chrome too, but didn't). Anyway, fixed now.

**Closed by markmacgillivray** 2016-11-28 12:16 UTC
Labels: Blocked: Test, JISC, question / discussion, Website

**Comment by JosephMcArthur** [comment] 2016-11-28 12:18
Beautiful, thanks. It's far more pleasing now ;)
